### ISSUE TITLE
error: Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by JB-Vexx** [nmaggioni/UniFiMoodleDownloader#5]
Can't access to the moodle page:

![2022-03-22_16-14](https://user-images.githubusercontent.com/64423428/159515435-2a234f1c-1b35-4dc4-810e-78b3f8064b1c.png)

I suppose that after entering the username and password it can't find the "submit" button 

`lib/scraper.js:151:   await page.click('button[name="submit"][type="submit"]');`

**Comment by nmaggioni** [comment]
Thanks for the report, should be fixed now. Feel free to reopen if not.
